name: Dependency Submission

on:
  schedule:
    - cron: '0 0 * * *' # Daily at midnight UTC
  workflow_dispatch:

permissions:
  contents: read

# Prevent multiple runs from clogging the queue
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CI_CHUNK_SIZE: 65

jobs:
  prepare:
    name: Prepare chunks
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate-matrices.outputs.matrix || steps.empty-matrices.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Get last successful CI commit
        uses: nrwl/nx-set-shas@afb73a62d26e41464e9254689e1fd6122ee683c1 # v5.0.1
        with:
          fallback-sha: 4b825dc642cb6eb9a060e54bf8d69288fbee4904

      - name: Check for relevant file changes
        id: check-files
        uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96 # v47.0.6
        with:
          base_sha: ${{ env.NX_BASE }}
          files: |
            gradle/libs.versions.toml
            **/*.gradle
            **/*.gradle.kts
            buildSrc/**
            .github/workflows/dependency-submission.yml

      - id: generate-matrices
        name: Create output matrices
        if: steps.check-files.outputs.any_changed == 'true'
        run: |
          python ./.github/scripts/generate-build-matrices.py "$NX_BASE" Release

      - id: empty-matrices
        name: Empty output matrices
        if: steps.check-files.outputs.any_changed != 'true'
        run: |
          echo "matrix={\"chunk\": []}" >> $GITHUB_OUTPUT

  submit:
    name: Submit Chunks (${{ matrix.chunk.number }})
    needs: prepare
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: ${{ toJson(fromJson(needs.prepare.outputs.matrix).chunk) != '[]' }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.prepare.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: 17
          distribution: temurin

      - name: Submit Dependencies
        uses: gradle/actions/dependency-submission@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0
        with:
          additional-arguments: |
            ${{ join(matrix.chunk.modules, ' ') }}
